path:
  out: /root/reDeco/zksnark/
  MPC: /root/reDeco/zksnark/bin/c++/2pc/
  libsnark: /root/reDeco/zksnark/bin/c++/jsnark_interface/
  package: /root/reDeco/zksnark/bin/
file:
  circuit: redact_suffix_circuit.arith
  input: redact_suffix_circuit.in
  name: redact_suffix_circuit
  prover: run_generate_prove
  verifier: run_verify
package:
  generator: examples.generators.deco.RedactSuffixCircuitGenerator
